name: Package Application with Pyinstaller

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install xmllint
      run: sudo apt install python3-tk

    - name: Package Application Windows
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: src

    - name: Package Application Linux
      uses: JackMcKew/pyinstaller-action-linux@main
      with:
        path: src

    - uses: actions/upload-artifact@v2
      with:
        name: tw-automapper-windows
        path: src/dist/windows/automapper

    - uses: actions/upload-artifact@v2
      with:
        name: tw-automapper-linux
        path: src/dist/linux/automapper
