name: Package Application with Pyinstaller

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install tk, upx
      run: sudo apt install -y python3-tk upx

    - name: Package Application Windows
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: src

    # - name: Package Application Linux
    #   uses: JackMcKew/pyinstaller-action-linux@main
    #   with:
    #     path: src

    # - name: copy windows executables
    #   run: cp src/dist/windows/tw-mapgen.exe tw-mapgen-windows.exe

    # - name: copy linux executables
    #   run: cp src/dist/linux/tw-mapgen tw-mapgen-linux

    # - name: Commit executables
    #   uses: EndBug/add-and-commit@v7
    #   with:
    #     add: '["tw-mapgen-windows.exe","tw-mapgen-linux"]'
    #     author_name: "Github Action"
    #     message: 'update executables'

    - uses: actions/upload-artifact@v2
      with:
        name: tw-mapgen-windows.exe
        path: src/dist/windows/tw-mapgen.exe

    # - uses: actions/upload-artifact@v2
    #   with:
    #     name: tw-mapgen-linux
    #     path: src/dist/linux/tw-mapgen
